// Test Requirements
#include "unity.h"
#include "he_test_definitions.h"
#include "lua_setup.h"

// Module Under Test
#include "user_repo.h"

// Internal Dependencies (Not Mocked)
#include "util.h"

// Third-Party Mocks
#include "mock_zlog.h"

TEST_FIXTURES();

char *valid = "test";
char *invalid = "fail";

void setUp(void) {
  FIXTURE_SERVER_CONN_SETUP();

  IGNORE_LOGGING_SETUP();

  lua_setup(&server);
}

void tearDown(void) {
  lua_teardown(&server);

  FIXTURE_SERVER_CONN_TEARDOWN();
}

void test_he_user_is_valid(void) {
  bool res = he_check_user_is_valid(&server, valid);

  TEST_ASSERT_TRUE(res);

  res = he_check_user_is_valid(&server, invalid);

  TEST_ASSERT_FALSE(res);
}

void test_he_check_auth(void) {
  bool res = false;

  res = he_check_auth(&server, valid, valid);

  TEST_ASSERT_TRUE(res);

  res = he_check_auth(&server, valid, invalid);

  TEST_ASSERT_FALSE(res);
  res = he_check_auth(&server, invalid, valid);

  TEST_ASSERT_FALSE(res);

  res = he_check_auth(&server, invalid, invalid);

  TEST_ASSERT_FALSE(res);
}

void test_he_check_auth_nulls(void) {
  bool res = false;

  res = he_check_auth(&server, valid, NULL);

  TEST_ASSERT_FALSE(res);

  res = he_check_auth(&server, NULL, valid);

  TEST_ASSERT_FALSE(res);

  res = he_check_auth(&server, NULL, NULL);

  TEST_ASSERT_FALSE(res);
}

void test_he_check_auth_empty(void) {
  bool res = false;

  res = he_check_auth(&server, valid, "");

  TEST_ASSERT_FALSE(res);

  res = he_check_auth(&server, "", valid);

  TEST_ASSERT_FALSE(res);

  res = he_check_auth(&server, "", "");

  TEST_ASSERT_FALSE(res);
}

void test_he_update_auth_token_public_key(void) {
  server.auth_token_public_key_path = "test/support/test_auth_token.pub";

  he_update_auth_token_public_key(&server);

  TEST_ASSERT_NOT_NULL(server.auth_token_public_key);

  static const char *testing_public_key =
      "-----BEGIN PUBLIC KEY-----\n"
      "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArqHtgUkuLFkcXJ5VSiPn\n"
      "mW4E1bUYjCNcUjnR5W/UU+aDEBI8XfcRoUlNSLMmZj7I9QXKY45HbsWnoU9pLp7D\n"
      "R2XeqoFNykTzjCbyJRnXrJFjzAFwTiSYYvCi9vdrwb4P0dp7X9w3HvMSLYC659lG\n"
      "RQRX9PckQoMnJDdQcJph0F+OQ4Jp7QqkBevAw5hvRC6Jy1FbpKpug0l7dktqDivr\n"
      "DhffHYwx7+mcnnwP+5WxfYXArfWTgLIXEPcJtFxr/xzzjy19ZLdBDAThQF1cfWqq\n"
      "h2aQjdOuQp1vNKFkygnmeI7mc33IgMOHuyI9TIWZBepjzEZUCaj/drcwoHM/AeuF\n"
      "3QIDAQAB\n"
      "-----END PUBLIC KEY-----\n";

  TEST_ASSERT_EQUAL_STRING(testing_public_key, server.auth_token_public_key);

  jefree((void *)server.auth_token_public_key);
}

void test_he_check_auth_token_nulls(void) {
  TEST_ASSERT_FALSE(he_check_auth_token(NULL, (const uint8_t *)"token", 5));
  TEST_ASSERT_FALSE(he_check_auth_token(&conn, NULL, 5));
  TEST_ASSERT_FALSE(he_check_auth_token(&conn, (const uint8_t *)"token", 0));

  he_server_connection_t conn2 = {0};
  TEST_ASSERT_FALSE(he_check_auth_token(&conn2, (const uint8_t *)"token", 5));
}

void test_he_check_auth_token_legacy_success(void) {
  // Testing public key from lua/spec/he_auth_token_spec.lua
  const char *testing_public_key =
      "-----BEGIN PUBLIC KEY-----\n"
      "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu5d2hIMxKzKtDduANJKZ\n"
      "cNt1Ptk4EBNY/uI9qcjENFcJZvZWxQ9bVMMuvM/hHvGmUd1GV7wlau3xGZ+VC9ZO\n"
      "/LsR50o3X7HDCHZix1BgRQ1pHXHcyEXEfZbsFrTOupa2RGqY4KB2m2wr0PpO/fSx\n"
      "04bptNMUWDj3xhRrAb2fl3HOKT0F1t3XDnMlisn7osAuDtjHHM7EUnfYXGqeE4jr\n"
      "EG+fsQFDANMB1whvnNA4UQ3L66FZmvk5UbPXRMF0R8cC5Dxm2AeyHItPX16sTqE8\n"
      "7SocclFa4MfpIq/roEU6F0R1YKHV7kPbnTrOrumYFGmJikoZ924lKQw20h1PQkh8\n"
      "9wIDAQAB\n"
      "-----END PUBLIC KEY-----";
  server.auth_token_public_key = testing_public_key;

  // Testing token generated by lua/spec/he_auth_token_spec.lua
  const char *token =
      "eyJhbGciOiJSUzI1NiJ9."
      "eyJuYmYiOjE2OTM0NzM4NzUsImlhdCI6MTY5MzQ3Mzg3NCwiZXhwIjoyMDAwMDAwMDAwLCJzY29wZSI6Im9wZW5pZCBw"
      "cm9maWxlIGVtYWlsIiwiaXNzIjoiaHR0cHM6XC9cL2xvY2FsaG9zdFwvIiwia3BfdXNlciI6Imtybjo6aWFtOjp4dnBu"
      "OnVzZXI6MTZkM2NhNzktMjBiMy00MGViLTk3OTMtZWE1NzE3YWU1NGQzIiwic3ViIjoibG9jYWwifQ."
      "Gi0IebVzvdZ78gdyPihlWkB-EGqLmeEmt-55O_jf6rbBFvtNbE-"
      "pDhKLXeMAyKb8GiMGDgWazOqiAF74YfA1ZFdLmM4E6Xv_35USy4P_"
      "ZK4oRTk9oFd0DiyvcsLQY3nzECJA8ULHcZjVKd0DpERj322rFiBEB15vljnWhM8vyYpDyVxh5vNeWkRC4NLVHE6HRsS4"
      "o6nKTjk9UhiJqNpfx-QJHslzsEjP_4P2jRtCq62HsYaMVgsPzqFINhYuZ-Xfy_eixpzf1_"
      "Ln3OjzvQ3FSFDKMywT28GfpylWUB38x5V72NxRHipCa_jGI-qUhWOkhKaxwyHV0JZJB-2TpKIzng";
  TEST_ASSERT_TRUE(he_check_auth_token(&conn, (const uint8_t *)token, strlen(token)));
}

void test_he_check_auth_token_legacy_fail(void) {
  // Testing public key from lua/spec/he_auth_token_spec.lua
  const char *testing_public_key =
      "-----BEGIN PUBLIC KEY-----\n"
      "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu5d2hIMxKzKtDduANJKZ\n"
      "cNt1Ptk4EBNY/uI9qcjENFcJZvZWxQ9bVMMuvM/hHvGmUd1GV7wlau3xGZ+VC9ZO\n"
      "/LsR50o3X7HDCHZix1BgRQ1pHXHcyEXEfZbsFrTOupa2RGqY4KB2m2wr0PpO/fSx\n"
      "04bptNMUWDj3xhRrAb2fl3HOKT0F1t3XDnMlisn7osAuDtjHHM7EUnfYXGqeE4jr\n"
      "EG+fsQFDANMB1whvnNA4UQ3L66FZmvk5UbPXRMF0R8cC5Dxm2AeyHItPX16sTqE8\n"
      "7SocclFa4MfpIq/roEU6F0R1YKHV7kPbnTrOrumYFGmJikoZ924lKQw20h1PQkh8\n"
      "9wIDAQAB\n"
      "-----END PUBLIC KEY-----";
  server.auth_token_public_key = testing_public_key;

  // A invalid token
  const char *token =
      "eyJhbGciOiJSUzI1NiJ9."
      "eyJuYmYiOjE2OTM0NzM4NzUsImlhdCI6MTY5MzQ3Mzg3NCwiZXhwIjoyMDAwMDAwMDAwLCJzY29wZSI6Im9wZW5pZCBw"
      "cm9maWxlIGVtYWlsIiwiaXNzIjoiaHR0cHM6XC9cL2xvY2FsaG9zdFwvIiwia3BfdXNlciI6Imtybjo6aWFtOjp4dnBu"
      "OnVzZXI6MTZkM2NhNzktMjBiMy00MGViLTk3OTMtZWE1NzE3YWU1NGQzIiwic3ViIjoibG9jYWwifQ."
      "Gi0IebVzvdZ78gdyPihlWkB-EGqLmeEmt-55O_jf6rbBFvtNbE-"
      "pDhKLXeMAyKb8GiMGDgWazOqiAF74YfA1ZFdLmM4E6Xv_35USy4P_"
      "o6nKTjk9UhiJqNpfx-QJHslzsEjP_4P2jRtCq62HsYaMVgsPzqFINhYuZ-Xfy_eixpzf1_"
      "Ln3OjzvQ3FSFDKMywT28GfpylWUB38x5V72NxRHipCa_jGI-qUhWOkhKaxwyHV0JZJB-2TpKIzng";
  TEST_ASSERT_FALSE(he_check_auth_token(&conn, (const uint8_t *)token, strlen(token)));
}

void test_he_check_auth_token_dip_success(void) {
  server.is_dip_enabled = true;
  server.auth_token_config = "lua/support/auth_token_dip.json";
  server.auth_token_script = "lua/he_auth_token.lua";

  // Load auth token config
  he_load_auth_token_config(&server);

  // Testing token generated via command: `TESTING_DIP=1.2.3.4 busted --filter='dip'`
  const char *token =
      "eyJraWQiOiJ4di1kaXAtbG9jYWwtdGVzdGluZyIsImFsZyI6IlJTMjU2In0."
      "eyJuYmYiOjE3MTk4NDY5MzksImlhdCI6MTcxOTg0Njk0OSwiZW50aXRsZW1lbnRzIjp7Inh2LnZwbi5kaXAuZGV0YWls"
      "cyI6eyJpcCI6IjEuMi4zLjQifX0sImlzcyI6Inh2LmRjdHMiLCJhdWQiOiJ4di52cG4uZGlwIiwiZXhwIjoyMDAwMDAw"
      "MDAwfQ.VIYx8ukWdVzj1IbBdZV9t7V5HydDjUUsfNO2stPRQ4V--HB1IZGPmESfLKXmS53v_5awLd9QgDQNMW6Scty_"
      "nnaWrjJtUFoQHMR5XiQ7qmGv7pDnlJAY9U-Isqk5w8NLwxlzouguk7yXJ6mhE1fdS7-Ee0HbcdjLKSYrBqj_"
      "Wep2E3LS-I133mTrJ2g2AyAMm4J0fa0M_RLRe33wDGg_lcXtNdzB_qBcmGs1CvXGN3g_-GcPcNuXP8DbtbmG3-tlU_"
      "BRRsWw_5yBA5jm4BHfLoI19sGizr1wviU5zJ9BqkbykyeaYm1srQ43fqzwFAxvuwWq6uJUfYnkU_LRuxirMQ";
  // Auth success if the connection's destination ip is correct
  conn.dip_addr.sin_addr.s_addr = ip2int("1.2.3.4");
  TEST_ASSERT_TRUE(he_check_auth_token(&conn, (const uint8_t *)token, strlen(token)));
}

void test_he_check_auth_token_dip_fail(void) {
  server.is_dip_enabled = true;
  server.auth_token_config = "lua/support/auth_token_dip.json";
  server.auth_token_script = "lua/he_auth_token.lua";

  // Load auth token config
  he_load_auth_token_config(&server);

  // Testing token generated via command: `TESTING_DIP=1.2.3.4 busted --filter='dip'`
  const char *token =
      "eyJraWQiOiJ4di1kaXAtbG9jYWwtdGVzdGluZyIsImFsZyI6IlJTMjU2In0."
      "eyJuYmYiOjE3MTk4NDY5MzksImlhdCI6MTcxOTg0Njk0OSwiZW50aXRsZW1lbnRzIjp7Inh2LnZwbi5kaXAuZGV0YWls"
      "cyI6eyJpcCI6IjEuMi4zLjQifX0sImF1ZCI6ImNnLnZwbi5kaXAiLCJleHAiOjIwMDAwMDAwMDB9."
      "RWZq4c9GunBYNd5V8bmfr2Pjgr9nnNhPQwJEF3gwxnSeV4ogL5ie7EcrplSiqyIoVhJVEfVCVv8bNPQEC136BFA8fXnW"
      "h_xPqD_B2jbIFvNvLouXqkSacVqaOqx_sfEXyzmAZxhIJMHhhc2XISL3GA7e2eEzRNVU6S8H9GVxSLPDdpW_"
      "34hpqKJLSQmw4ScG7tikrw0dqJt6paqOuuSfQDBNSlvmlytJUytpDFmAk81ROsZ1EV6sysLNsgVEaBy4-"
      "nn9eSmJXvJ3gHScTjziHpRf114AYyoB0pAF5JnqJvbLfEvLiWg_8mih_nSif8OzevvGfD5ggRIg6UoqCFsTlA";

  // Auth fail if the connection's destination ip doesn't match
  conn.dip_addr.sin_addr.s_addr = ip2int("4.3.2.1");
  TEST_ASSERT_FALSE(he_check_auth_token(&conn, (const uint8_t *)token, strlen(token)));
}
